export const subscriptionPlans = [
  {
    planName: "community",
    planDescription: "Free core automation with basic limits.",
    planPrice: 0.0,
    planCurrency: "INR",
    planInterval: "month",
    highlighted: false,
    polarProductId: process.env.NEXT_PUBLIC_POLAR_COMMUNITY,
    polarProductSlug: "community",
    planFeatures: [
      "Visual workflow editor",
      "Manual + webhook triggers",
      "Encrypted local credentials",
      "100 executions/month",
    ],
  },
  {
    planName: "pro",
    planDescription: "Fast automation + AI + collaboration.",
    planPrice: 399.0,
    planCurrency: "INR",
    planInterval: "month",
    highlighted: true,
    polarProductId: process.env.NEXT_PUBLIC_POLAR_PRO,
    polarProductSlug: "pro",
    planFeatures: [
      "AI model nodes (streaming)",
      "Realtime execution monitoring",
      "5,000 executions/month",
      "5 collaborators",
    ],
  },
  {
    planName: "enterprise",
    planDescription: "Scale + security + SSO.",
    planPrice: 4999.0,
    planCurrency: "INR",
    planInterval: "month",
    highlighted: false,
    polarProductId: process.env.NEXT_PUBLIC_POLAR_ENTERPRISE,
    polarProductSlug: "enterprise",
    planFeatures: [
      "Unlimited executions",
      "Enterprise SSO (SAML/SAML-like)",
      "Managed secrets vault",
      "24/7 support",
    ],
  },
] as const;
